First cleaning of the plugin
call-learning/moodle-block_rss_thumbnails pull request #1
Opened 2022-09-14 15:38 UTC by martin-call-learning

Still some issues to fix.
This pull request if you have some time so you can see what i've done and so our meeting tomorrow would be even more interesting. ;)
As I told you in Matrix there is this issue remaining :
```bash
Potentially polymorphic call. renderer_base does not have members in its hierarchy
```
And another wich comes from an higher class
```bash
Expected parameter of type 'context', 'null|stdClass' provided
```
And some imports that are unknown but I think I have to lay it as it was

2022-10-14 13:33 UTC, laurentdavid requested changes
Salut Martin,

De très bon changements et optimisations en général. Le seul bémol: il faudrait tester cela avec le feed ici https://www.imt.fr/feed/ car il y a quelques erreurs fatales dues à des changements de types.

2022-10-14 13:33 UTC, laurentdavid commented on block_rss_thumbnails.php
> +    private bool $hasfailedfeeds = false;
Attention ici on contraint les utilisateurs à utiliser PHP 7.4. C'est désiré mais pas forcément le cas pour tout le monde et jusqu'à Moodle 3.11, on ne requiers que du 7.3. Sachant qu'en PHP 7.3 la déclaration ici va empêcher le bloc de fonctionner.

2022-10-14 13:33 UTC, laurentdavid commented on block_rss_thumbnails.php
> +        // Initialise block content object.
Bien vu !

2022-10-14 13:33 UTC, laurentdavid commented on block_rss_thumbnails.php
> +    protected function get_footer($feedrecords) : block_rss_client\output\footer {
Là aussi voir la compatibilité PHP. A mon avis c'est bon car c'est du PHP 7.3+.

2022-10-14 13:33 UTC, laurentdavid commented on block_rss_thumbnails.php
> +    public function get_feed($feedrecord, $maxentries, $showtitle) : ?block_rss_client\output\feed {
La et au dessus: tu as importé le namespace pour avoir la classe feed, donc le mieux c'est d'utiliser "feed" aussi ici.

2022-10-14 13:33 UTC, laurentdavid commented on classes/output/block.php
> +        parent::__construct($feeds);
Bien vu!

2022-10-14 13:33 UTC, laurentdavid commented on classes/output/item.php
> +    protected ?string $categories = null;
Ici c'est un tableau ! Tu verras, une erreur fatale se produit ici.

2022-10-14 13:33 UTC, laurentdavid commented on block_rss_thumbnails.php
> +    protected function get_footer($feedrecords) : block_rss_client\output\footer {
Attention: c'est  ?block_rss_client\output\footer (sinon une erreur fatale se produit)

2022-10-14 13:33 UTC, laurentdavid commented on version.php
> -$plugin->version   = 2021012200;        // The current plugin version (Date: YYYYMMDDXX).
Tu peux incrémenter la version ici, surtout si tu as changé un language string (ça rafraîchira le cache).

2022-10-14 13:34 UTC, laurentdavid reviewed
Je mettrai ici 7.3, 7.4 et 8.0. Comme ça on couvre du 3.9 à 4.x
Il faudra rebase le commit et le squasher avec le précédent.

2022-10-14 13:38 UTC, laurentdavid commented on tests/block_rss_thumbnails_test.php
> +        require_once("$CFG->libdir/simplepie/moodle_simplepie.php");
Là il y a un soucis dû à autre chose que ton changement. Il faudrait déclarer la variable $CFG.

2022-10-17 07:15 UTC, martin-call-learning commented on block_rss_thumbnails.php
> +    private bool $hasfailedfeeds = false;
Oui, je me souviens que j'avais commencé à enlever les types, mais j'ai dû en oublier, je me mets dessus

2022-10-17 07:16 UTC, martin-call-learning commented on block_rss_thumbnails.php
> +    protected function get_footer($feedrecords) : block_rss_client\output\footer {
Je vais me renseigner

2022-10-17 07:18 UTC, martin-call-learning commented on classes/output/item.php
> +    protected ?string $categories = null;
Bizarre que j'aie mis ça haha, surtout que je savais que c'est un tableau

2022-10-20 14:32 UTC, merged